name: Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # triggers release only for tags like v1.0.0
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          mkdir -p dist
          echo "Building for ${{ matrix.goos }} / ${{ matrix.goarch }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/dbctui-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/dbctui

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbctui-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/dbctui-${{ matrix.goos }}-${{ matrix.goarch }}*

      # Release step — only runs for tagged commits
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
